u19325658_Hw3/Models/FileModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace u19325658_Hw3.Models
{
    public class FileModel
    {
        [Display(Name = "File Name")]
        public string FileName { get; set; }

        [Required(ErrorMessage = "Please select file.")]
        [Display(Name = "Browse File")]
        public HttpPostedFileBase[] Files { get; set; }
    }
}

u19325658_Hw3/Controllers/FileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using u19325658_Hw3.Models;

namespace u19325658_Hw3.Controllers
{
    public class FileController : Controller
    {
        // GET: File
        public ActionResult Index()
        {
            string[] filePath = Directory.GetFiles(Server.MapPath("~/Media/Documents"));
            List<FileModel> Files = new List<FileModel>();
            foreach(string filepaths in filePath)
            {
                Files.Add(new FileModel { FileName = Path.GetFileName(filepaths) });
            }

            return View(Files);
        }

        public FileResult DownloadFile(string fileName)
        {
            //Build the File Path.

            string path = Server.MapPath("~/Media/Documents/") + fileName;

            //Read the File data into Byte Array.
            //Use a byte array becasue of octet-stream.

            byte[] bytes = System.IO.File.ReadAllBytes(path);

            //Send the File to Download.

            //The OCTET-STREAM format is used for file attachments on the Web with an
            //unknown file type. These .octet-stream files are arbitrary binary data
            //files that may be in any multimedia format.

            return File(bytes, "application/octet-stream", fileName);
        }

        public ActionResult DeleteFile(string fileName)
        {
            //Delete requires reading the files and then the allocation of a file path.
            //The file is then deleted based on the identified file path.

            string path = Server.MapPath("~/Media/Documents/") + fileName;
            byte[] bytes = System.IO.File.ReadAllBytes(path);

            System.IO.File.Delete(path);

            return RedirectToAction("Index");
        }
    }
}

u19325658_Hw3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using u19325658_Hw3.Models;

namespace u19325658_Hw3.Controllers
{
    public class HomeController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(HttpPostedFileBase files, string mediaUpload)
        {
            if (files != null && files.ContentLength > 0)
            {
                if(mediaUpload == "document")
                {
                    var fileName = Path.GetFileName(files.FileName);
                    var path = Path.Combine(Server.MapPath("~/Media/Documents"), fileName);
                    files.SaveAs(path);
                }

                else if(mediaUpload == "image")
                {
                    var fileName = Path.GetFileName(files.FileName);
                    var path = Path.Combine(Server.MapPath("~/Media/Images"), fileName);
                    files.SaveAs(path);
                }

                else if(mediaUpload == "video")
                {
                    var fileName = Path.GetFileName(files.FileName);
                    var path = Path.Combine(Server.MapPath("~/Media/Videos"), fileName);
                    files.SaveAs(path);
                }
            }
            return RedirectToAction("Index");

        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }


        
    }
}

u19325658_Hw3/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using u19325658_Hw3.Models;

namespace u19325658_Hw3.Controllers
{
    public class ImageController : Controller
    {
        // GET: Image
        public ActionResult Index()
        {
            string[] filePath = Directory.GetFiles(Server.MapPath("~/Media/Images"));
            List<FileModel> Files = new List<FileModel>();
            foreach (string filepaths in filePath)
            {
                Files.Add(new FileModel { FileName = Path.GetFileName(filepaths) });
            }

            return View(Files);
        }

        public FileResult DownloadFile(string fileName)
        {
            //Build the File Path.

            string path = Server.MapPath("~/Media/Images/") + fileName;

            //Read the File data into Byte Array.
            //Use a byte array becasue of octet-stream.

            byte[] bytes = System.IO.File.ReadAllBytes(path);

            //Send the File to Download.

            //The OCTET-STREAM format is used for file attachments on the Web with an
            //unknown file type. These .octet-stream files are arbitrary binary data
            //files that may be in any multimedia format.

            return File(bytes, "application/octet-stream", fileName);
        }

        public ActionResult DeleteFile(string fileName)
        {
            //Delete requires reading the files and then the allocation of a file path.
            //The file is then deleted based on the identified file path.

            string path = Server.MapPath("~/Media/Images/") + fileName;
            byte[] bytes = System.IO.File.ReadAllBytes(path);

            System.IO.File.Delete(path);

            return RedirectToAction("Index");
        }
    }
}

u19325658_Hw3/Controllers/VideoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using u19325658_Hw3.Models;

namespace u19325658_Hw3.Controllers
{
    public class VideoController : Controller
    {
        // GET: Video
        public ActionResult Index()
        {
            string[] filePath = Directory.GetFiles(Server.MapPath("~/Media/Videos"));
            List<FileModel> Files = new List<FileModel>();
            foreach (string filepaths in filePath)
            {
                Files.Add(new FileModel { FileName = Path.GetFileName(filepaths) });
            }

            return View(Files);
        }

        public FileResult DownloadFile(string fileName)
        {
            //Build the File Path.

            string path = Server.MapPath("~/Media/Videos/") + fileName;

            //Read the File data into Byte Array.
            //Use a byte array becasue of octet-stream.

            byte[] bytes = System.IO.File.ReadAllBytes(path);

            //Send the File to Download.

            //The OCTET-STREAM format is used for file attachments on the Web with an
            //unknown file type. These .octet-stream files are arbitrary binary data
            //files that may be in any multimedia format.

            return File(bytes, "application/octet-stream", fileName);
        }

        public ActionResult DeleteFile(string fileName)
        {
            //Delete requires reading the files and then the allocation of a file path.
            //The file is then deleted based on the identified file path.

            string path = Server.MapPath("~/Media/Videos/") + fileName;
            byte[] bytes = System.IO.File.ReadAllBytes(path);

            System.IO.File.Delete(path);

            return RedirectToAction("Index");
        }
    }
}

u19325658_Hw3/Views/File/Index.cshtml
@using u19325658_Hw3.Models;
@model List<FileModel>

@{
    ViewBag.Title = "Index";
}

<h2>FileSafe Database</h2> <br />
<h4>Here you will find all your uploaded documents</h4>
<br />

<table class="table">
    <tr>
        <th>
            File Name
        </th>
        <th>
            DOWNLOAD OPTION
        </th>
        <th>
            DELETE OPTION
        </th>
    </tr>

@foreach (FileModel file in Model) {
    <tr>
       <td>
           @file.FileName
       </td>
       <td>
           <button>
               @Html.ActionLink("Download", "DownloadFile",
              new { fileName = file.FileName})
           </button>
       </td>
       <td>
           <button>
               @Html.ActionLink("Delete", "DeleteFile",
              new { fileName = file.FileName })
           </button>
       </td>
    </tr>
}

</table>

u19325658_Hw3/Views/Home/About.cshtml
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-6"> 
            <h2>About Me</h2>            
            <h3>Getting to know Aadil Bissessar..</h3>
            <p>
                My name is Aadil Bissessar, I am 21 years old and I am an Informatics student at the University of Pretoria. I am a relentless and hard working individual who loves to seek a challenge. I am an outgoing person with a broad range of interests an hobbies. Some of my interets are Day Trading, sports, learning new skills, business and many more. I am a quick learner who is able to grasp new concepts and skills relatively quick and once I know how to do something I do not forget. My goals are to persue a career in Informatics and to one day be a successful businessman.
            </p>
        </div>
        <div class="col-sm-6">
            <h3>Aadil Bissessar</h3>
            <br/>
            <img src="https://img.ibxk.com.br/2021/06/10/10152930440231.jpg" height="300" width="450"/>
        </div>
    </div>
</div>

u19325658_Hw3/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}


<div class="header">
    <h2>FileSafe</h2>
    <h3>What we FileSafe is all about</h3>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-6">
            <p>
                FileSafe is a media uploading system where you can upload Documents, Images or videos from your PC or computer.
            </p>
        </div>
        <div class="col-sm-6">
            <p>Please select the type of file you wish upload:</p>
            <br />
            @using (Html.BeginForm("Index", "Home", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div>
                    @Html.RadioButton("mediaUpload", "document") Document <br />
                    @Html.RadioButton("mediaUpload", "image") Image <br />
                    @Html.RadioButton("mediaUpload", "video") Video <br />
                </div>
                <br />
                <div><input type="file" name="files" /></div>
                <br />
                <div><input type="submit" value="Upload" /></div>
            }

        </div>
    </div>
</div>

u19325658_Hw3/Views/Image/Index.cshtml
@using u19325658_Hw3.Models;
@model List<FileModel>

<head>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.css" type="text/css" media="screen" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js"></script>
</head>

<script>
    $(document).ready(function ($) {
        $(".gallery a").fancybox();
    });
</script>

<h2>FileSafe Database</h2>
<br />
<h4>Uploaded Images</h4>
<br />
<div class="container-fluid">
    <div class="row">
        @foreach (FileModel file in Model)
        {
        <div class="col-sm-4">

            <div class="gallery">
                <a title="Photo" href="@Url.Content("~/Media/Images/")@file.FileName">
                    <img src="@Url.Content("~/Media/Images/")@file.FileName" height="350" width="350" />
                </a>
            </div>
            <br />
            <p>@file.FileName</p>
            <br />
            <button>
                @Html.ActionLink("Download", "DownloadFile",
                new { fileName = file.FileName })
            </button>
            <button>
                @Html.ActionLink("Delete", "DeleteFile",
                new { fileName = file.FileName })
            </button>

        </div>
        }
    </div>
</div>

u19325658_Hw3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Files", "Index", "File")</li>
                    <li>@Html.ActionLink("Images", "Index", "Image")</li>
                    <li>@Html.ActionLink("Videos", "Index", "Video")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

u19325658_Hw3/Views/Video/Index.cshtml
@using u19325658_Hw3.Models;
@model List<FileModel>

<head>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.css" type="text/css" media="screen" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js"></script>
</head>

<script>
    $(document).ready(function ($) {
        $(".gallery a").fancybox();
    });
</script>

<h2>FileSafe Database</h2>
<br />
<h4>Uploaded Videos</h4>
<br />
<div class="container-fluid">
    <div class="row">
        @foreach (FileModel file in Model)
        {
        <div class="col-sm-4">

            <div class="gallery">
                <a href="@Url.Content("~/Media/Videos/")@file.FileName">
                    <video src="@Url.Content("~/Media/Videos/")@file.FileName" height="350" width="350"></video>
                </a>
            </div>
            <p>@file.FileName</p>
            <br />
            <button>
                @Html.ActionLink("Download", "DownloadFile",
               new { fileName = file.FileName })
            </button>
            <button>
                @Html.ActionLink("Delete", "DeleteFile",
               new { fileName = file.FileName })
            </button>

        </div>
        }
    </div>
</div>